---
# tasks file for archive
  - name: Compressing Folders
    archive:
        path: /home/adinath/hello
        dest: /home/adinath/Xyz/hello.tgz
  
  - name: create a zip archive of folder
    archive:
        path: /home/adinath/hello/hiiii
        dest: /home/adinath/hello/file.zip
        format: zip

  - name: create multiple files
    archive:
        path:
           - /home/adinath/hello
           - /home/adinath/Xyz
           - /home/adinath/Public
        dest: /home/adinath/compressed/file.tar.bz2
